/*
Pushpinder Sekhon
251291426
March 28, 2023
The purpose of the lab is to create different methods to in order to multiply 2 matrices together, which are randomly generated by the user
*/

package Q2;//indicates package
import java.util.*;//imports multiple classes
import LA3Q.MyMethod;//imports MyMethod class
public class WeeklySaleDataPushpinder//indicates class
{
    private double[] sale;//initialises array

    public WeeklySaleDataPushpinder()//constructor method setting field to null
    {
        this.sale = null;//sets field to null

    }

    public WeeklySaleDataPushpinder(double[] sale)//constructor method setting value of field to argument of constructor
    {
        this.sale = sale;//sets value of field to argument of constructor

    }

    public double getAverageSale()//gets average of the array
    {
        double sum = 0;//initialises sum variable
        for (int i = 0; i < sale.length; i++)//loop which finds sum of all elements of array
        {
            sum = sum + sale[i];//finds sum of elements of array
        }
        double average = sum/sale.length;//calculates average using sum and length of array
        return average;//returns average

    }

    public double getHighestSale()//method gets highest value of sale array field
    {
        double max = 0;//initialises max variable
        for (int i = 0; i < sale.length; i++)//loop which determines highest value in array
        {
            if (max < sale[i])//if statement executes is value is higher than previous maximum
            {
                max = sale[i];//changes value of max
            }
        }

        return max;//returns highest value in array

    }

    public double getLowestSale()//method used to find the lowest value in the given array
    {
        double min = 99999;//sets min to very high value so that it must inevitably go lower than this
        for (int i = 0; i < sale.length; i++)//loop which runs through all elements in array finds the lowest of them all
        {
            if (min > sale[i])//conditional statement executes if min variable is less than element in array
            {
                min = sale[i];//replaces min value with element in array
            }
        }
        return min;//returns lowest value in array

    }

    public void displaySaleData()//displays array
    {
        System.out.print("[");//prints bracket
        for (int i = 0; i < sale.length; i++)//loop used to print all elements in array
        {
            System.out.printf("%.2f, ",sale[i]);//prints array element
        }
        System.out.print("\b\b]");//prints bracket and fixes formatting

    }

    public double getStandardDeviation()//method calculates standard deviation of all elements in the array
    {
        double standardDeviation;//initialises variable
        double sum = 0;//initialises variable and sets it to 0

        for (int i = 0; i < sale.length; i++)//calculates sum as part of the equation
        {
            sum = sum + Math.pow((sale[i] - getAverageSale()),2);//find sum using equation given
        }

        standardDeviation = Math.sqrt((sum/sale.length));//finds standard deviation using equation given

        return standardDeviation;//returns standard deviation

    }
}
