/*
Pushpinder Sekhon
251291426
March 28, 2023
The purpose of the lab is to create different methods to in order to multiply 2 matrices together, which are randomly generated by the user
*/

package Q2;//indicates package
import LA3Q.MyMethod;//imports MyMethod class
import java.util.*;//imports various classes
import java.io.*;//imports various classes related to files
public class WorkingWithFilesAndArrays//indicates class
{
    public static void main(String[] args) throws IOException//driver method
    {
        MyMethod.myHeader(4,2,"To demonstrate the use of text files and arrays in order to calculate the highest, lowest, average, and standard deviation of some elements");//prints header

        File file = new File("Datafile_LabAssignment4.txt");//creates reference variable for this file

        Scanner input = new Scanner(file);//creates reference variable for scanner

        double[] saleInfo = new double[7];//creates array reference variable of size 7

        for (int i = 0; i < saleInfo.length; i++)//loop populates array elements using the values given in the file
        {
            saleInfo[i] = input.nextDouble();//reads and stores the values in the file to the array elements
        }

        input.close();//closes file reference variable

        WeeklySaleDataPushpinder call = new WeeklySaleDataPushpinder(saleInfo);//reference variable to other class

        call.displaySaleData();//displays data
        System.out.printf("\nHighest weekly Sale: %.2f", call.getHighestSale());//prints highest value
        System.out.printf("\nLowest weekly Sale: %.2f", call.getLowestSale());//prints lowest value
        System.out.printf("\nAverage weekly Sale: %.2f", call.getAverageSale());//prints average value
        System.out.printf("\nStandard Deviation of Weekly Sale: %.2f", call.getStandardDeviation());//prints standard deviation

        FileWriter fw = new FileWriter("Datafile_LabAssignment4.txt",true);//new reference variable for FileWriter class, we need FileWriter class to use the printf method
        PrintWriter pw = new PrintWriter(fw);//new reference variable from PrintWriter class, we need this to append the file
        //both FileWriter and PrintWriter must be used together to append a file with printf methods

        System.out.println("\n.. Updating the file with the above info...");//prints statement

        pw.printf("\n\nHighest weekly Sale: %.2f", call.getHighestSale());//appends file with highest value
        pw.printf("\nLowest weekly Sale: %.2f", call.getLowestSale());//appends file with lowest value
        pw.printf("\nAverage weekly Sale: %.2f", call.getAverageSale());//appends file with average value
        pw.printf("\nStandard Deviation of Weekly Sale: %.2f", call.getStandardDeviation());//appends file with standard deviation
        pw.printf("\n\nReported by: Pushpinder Sekhon\n");//appends file
        pw.close();//closes file

        System.out.println("Closed the file.....");//prints statement

        MyMethod.myFooter(2);//prints footer
    }
}
